### ISSUE TITLE
Webhook support?

### ISSUE THREAD

**Issue by ryleu** [0x4e49434f4c45/amcdb#14]
many other mods allow using webhooks so that the player's username and icon show as a discord user in discord. This functionality is the only thing keeping me from using this mod, so i'd love to see it implemented

**Comment by 0x4e49434f4c45** [comment]
I've seen this implemented in other mods but didn't know if it was a feature users cared much about. I'll look into adding webhook support.

**Comment by ryleu** [comment]
It makes it much more clean and it's not super hard to do. https://discohook.com makes it pretty easy to make a template for your webhooks. If you're using an API wrapper for Discord, it probably has webhook support.

**Comment by s3nkwr** [comment]
If u add support for webhooks, please make support for FabricTailor skins

**Comment by 0x4e49434f4c45** [comment]
Webhook support has been implemented in [1.1.0](https://github.com/0x4e49434f4c45/amcdb/releases/tag/1.1.0)!

Unfortunately, adding support for FabricTailor skins was not practical. In general, while AMCDB strives to be *compatible* with other mods (i.e., it should behave in a sane way and not crash your server when other mods are installed), integrating with non-vanilla features of other mods is a completely different story and would quickly make this project un-maintainable.
