### ISSUE TITLE
Chat Exclusions

### ISSUE THREAD

**Issue by varinyc** [0x4e49434f4c45/amcdb#43]
A way to exclude certain messages originating from Minecraft forwarding to bridge, such as servers with multiple chat channels, or excluding teleport links or other forms of metadata sometimes used in MC chat that isn't intended to be read. 

Maybe config by Regex, just as a thought.

**Comment by varinyc** [comment]
I like the efficiency of your mod, and was hoping to use it with a Global/Local mod that let bridge only broadcast Global chat.

IDK how it does each chat, but I assume Regex for [global] in string would work. And also fix Xaeros map pings from appearing.

**Comment by 0x4e49434f4c45** [comment]
Can you link this global/local chat mod? I agree a regex is probably the way to go (perhaps separately configurable for player vs server messages?) but I want to make sure I fully understand this use case.

**Comment by varinyc** [comment]
Sorry for the delay:

https://github.com/stanlystark/SimpleChat

Global is normal text, everyone can see.
local is defined by an area/domain, similar to proximity voice, but also sometimes able to be filtered by "walls". Also includes team chats or other channels that organize communication that would no longer be considered "public".

If I were to use it like this, I would lbe able to omit local chat entirely from the discord the same as whispers are.
